networks:
  soccer-app-network:
    driver: bridge

services:
  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-service
    networks:
      - soccer-app-network
    ports:
      - "8761:8761"

  team-service:
    build:
      context: ./team-service
      dockerfile: Dockerfile
    networks:
      - soccer-app-network
    depends_on:
      - eureka-service
  #    deploy:
  #      replicas: 2
  #      resources:
  #        limits:
  #          cpus: "0.5"
  #          memory: "512M"
  #      restart_policy:
  #        condition: on-failure

  player-service:
    build:
      context: ./player-service
      dockerfile: Dockerfile
    networks:
      - soccer-app-network
    depends_on:
      - eureka-service
  #    deploy:
  #      replicas: 2
  #      resources:
  #        limits:
  #          cpus: "0.5"
  #          memory: "512M"
  #      restart_policy:
  #        condition: on-failure

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    networks:
      - soccer-app-network
    depends_on:
      - eureka-service
  #    deploy:
  #      replicas: 2
  #      resources:
  #        limits:
  #          cpus: "0.5"
  #          memory: "512M"
  #      restart_policy:
  #        condition: on-failure

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    networks:
      - soccer-app-network
    depends_on:
      - eureka-service
      - player-service
  #    deploy:
  #      replicas: 2
  #      resources:
  #        limits:
  #          cpus: "0.5"
  #          memory: "512M"
  #      restart_policy:
  #        condition: on-failure

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    networks:
      - soccer-app-network
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
      - auth-service
      - event-service
      - team-service
      - player-service
