services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: soccer_app
    ports:
      - "127.0.0.1:3307:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:8070:80"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      PMA_HOST: mysql