services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: soccer_app
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"