server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: player-service
          uri: lb://PLAYER-SERVICE
          predicates:
            - Path=/api/players/**

        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/teams/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: false
