name: Linter
on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  validate-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Run SQL file
        run: |
          sleep 20
          docker exec -i $(docker ps -q --filter name=cs4337-project-mysql-1) mysql -u root -p1234 soccer_app < db_setup.sql

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Verify Java syntax
        run: |
          javac -d bin src/main/java/com/example/soccerapp/HelloController.java

      - name: Clean up
        if: always()
        run: |
          docker compose down
