name: Linter
on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  validate-sql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: soccer_app
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=6

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove Docker container on port 3307
        run: |
          if [ "$(docker ps -q --filter publish=3307)" ]; then
            echo "Stopping container using port 3307..."
            docker stop $(docker ps -q --filter publish=3307)
          fi

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for MySQL to be healthy
        run: |
          sleep 15
          until [ "`docker inspect -f {{.State.Health.Status}} mysql`" == "healthy" ]; do
          sleep 10;
          done

      - name: Run SQL file
        run: |
          docker exec -i $(docker ps -q --filter name=mysql) mysql -u root -p1234 soccer_app < ../db_setup.sql

      - name: Clean up
        if: always()
        run: |
          docker compose down
