name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate SQL syntax
        run: |
          docker run --rm -v ${{ github.workspace }}:/sql-files mysql:5.7 \
          sh -c "mysql --user=root --password=rootpassword --execute='source db_setup.sql;'"