name: Linter
on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  validate-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Run SQL file
        run: |
          sleep 25
          docker exec -i $(docker ps -q --filter name=mysql) cs4337-project-mysql-1 -u root -p1234 soccer_app < ../db_setup.sql

      - name: Clean up
        if: always()
        run: |
          docker compose down
