name: Linter
on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  validate-sql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.40
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=6

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for MySql to be ready
        run: |
          sleep 15
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 10
          done

      - name: Validate SQL syntax
        run: |
          mysql -h 127.0.0.1 -u root --execute="source db_setup.sql;"
