name: Build and Test Microservices

on:
  pull_request:
    branches:
      - temp-main

name: Build Microservices

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Microservices
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Build API Gateway
      - name: Build API Gateway
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        if: always()

      # Build Auth Service
      - name: Build Auth Service
        working-directory: ./auth-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        if: always()

      # Build Eureka Service
      - name: Build Eureka Service
        working-directory: ./eureka-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        if: always()

      # Build Event Service
      - name: Build Event Service
        working-directory: ./event-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        if: always()

      # Build Manager Service
      - name: Build Manager Service
        working-directory: ./manager-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        if: always()

      # Build Player Service
      - name: Build Player Service
        working-directory: ./player-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        if: always()

      # Build Team Service
      - name: Build Team Service
        working-directory: ./team-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
        if: always()
