name: Build and Test Microservices

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Microservices
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Iterate through each microservice and build
      - name: Build and Test Microservices
        run: |
          services=("api-gateway" "auth-service" "eureka-service" "event-service" "manager-service" "player-service" "team-service")
          for service in "${services[@]}"; do
            echo "Building $service..."
            cd $service
            ./gradlew clean build --no-daemon
            if [ $? -ne 0 ]; then
              echo "Build failed for $service"
              exit 1
            fi
            cd ..
          done
          echo "All microservices built successfully!"
