name: Build and Test Microservices

on:
  pull_request:
    branches:
      - temp-main

jobs:
  build:
    name: Build Microservices
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Build API Gateway
      - name: Build API Gateway
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon > ../api-gateway-build.log 2>&1 || exit 1
        continue-on-error: true

      # Build Auth Service
      - name: Build Auth Service
        working-directory: ./auth-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon > ../auth-service-build.log 2>&1 || exit 1
        continue-on-error: true

      # Build Eureka Service
      - name: Build Eureka Service
        working-directory: ./eureka-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon > ../eureka-service-build.log 2>&1 || exit 1
        continue-on-error: true

      # Build Event Service
      - name: Build Event Service
        working-directory: ./event-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon > ../event-service-build.log 2>&1 || exit 1
        continue-on-error: true

      # Build Manager Service
      - name: Build Manager Service
        working-directory: ./manager-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon > ../manager-service-build.log 2>&1 || exit 1
        continue-on-error: true

      # Build Player Service
      - name: Build Player Service
        working-directory: ./player-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon > ../player-service-build.log 2>&1 || exit 1
        continue-on-error: true

      # Build Team Service
      - name: Build Team Service
        working-directory: ./team-service
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon > ../team-service-build.log 2>&1 || exit 1
        continue-on-error: true

      # Upload logs as artifacts
      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: |
            api-gateway-build.log
            auth-service-build.log
            eureka-service-build.log
            event-service-build.log
            manager-service-build.log
            player-service-build.log
            team-service-build.log